<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BloggingModule\Helper;

use MU\BloggingModule\Helper\Base\AbstractModelHelper;

/**
 * Helper implementation class for model layer methods.
 */
class ModelHelper extends AbstractModelHelper
{
    /**
     * Returns a desired sorting criteria for passing it to a repository method.
     *
     * @param string $objectType Name of treated entity type
     * @param string $sorting    The type of sorting (newest, random, default)
     *
     * @return string The order by clause
     */
    public function resolveSortParameter($objectType = '', $sorting = 'default')
    {
        return 'startdate' == $sorting ? 'startDate DESC' : parent::resolveSortParameter($objectType, $sorting);
    }
    // feel free to add your own convenience methods here
}
