<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\Form\Type\Field;

use MU\BloggingModule\Form\Type\Field\Base\AbstractMultiListType;

/**
 * Multi list field type implementation class.
 */
class MultiListType extends AbstractMultiListType
{
    // feel free to extend the base form type class here
}
