<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\Entity;

use MU\BloggingModule\Entity\Base\AbstractImageTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing image translations.
 *
 * This is the concrete translation class for image entities.
 *
 * @ORM\Entity(repositoryClass="MU\BloggingModule\Entity\Repository\ImageTranslationRepository")
 * @ORM\Table(name="mu_blogging_image_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class ImageTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
