<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\Entity;

use MU\BloggingModule\Entity\Base\AbstractImageEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for image entities.
 * @Gedmo\TranslationEntity(class="MU\BloggingModule\Entity\ImageTranslationEntity")
 * @ORM\Entity(repositoryClass="MU\BloggingModule\Entity\Repository\ImageRepository")
 * @ORM\Table(name="mu_blogging_image",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class ImageEntity extends BaseEntity
{
    // feel free to add your own methods here
}
