<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BloggingModule\Entity;

use MU\BloggingModule\Entity\Base\AbstractPostCategoryEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing post categories.
 *
 * This is the concrete category class for post entities.
 * @ORM\Entity(repositoryClass="\MU\BloggingModule\Entity\Repository\PostCategoryRepository")
 * @ORM\Table(name="mu_blogging_post_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class PostCategoryEntity extends BaseEntity
{
    // feel free to add your own methods here
}
