<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\Entity;

use MU\BloggingModule\Entity\Base\AbstractPostEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for post entities.
 * @Gedmo\TranslationEntity(class="MU\BloggingModule\Entity\PostTranslationEntity")
 * @ORM\Entity(repositoryClass="MU\BloggingModule\Entity\Repository\PostRepository")
 * @ORM\Table(name="mu_blogging_post",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 * @UniqueEntity(fields="slug", ignoreNull="false")
 */
class PostEntity extends BaseEntity
{
    /**
     * Sets the permalink.
     *
     * @param string $permalink
     *
     * @return void
     */
    public function setPermalink($permalink)
    {
        if ($this->permalink !== $permalink) {
            $this->permalink = isset($permalink) ? str_replace(' ', '-', $permalink) : str_replace(' ', '-', $this->title);
        }
    }
}
