<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

/**
 * MUBloggingModule post needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUBloggingModule_needleapi_post_baseInfo()
{
    $info = [
        // module name
        'module'  => 'MUBloggingModule',
        // possible needles
        'info'    => 'BLOGGING{POSTS|POST-postId}',
        // whether a reverse lookup is possible, needs MUBloggingModule_needleapi_post_inspect() function
        'inspect' => false
    ];

    return $info;
}
