<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.4 (http://modulestudio.de) at Fri Apr 14 14:26:08 CEST 2017.
 */

/**
 * Bootstrap called when application is first initialised at runtime.
 *
 * This is only called once, and only if the core has reason to initialise this module,
 * usually to dispatch a controller request or API.
 */
$container = ServiceUtil::get('service_container');


// check if own service exists (which is not true if the module is not installed yet)
if ($container->has('mu_blogging_module.archive_helper')) {
    $container->get('mu_blogging_module.archive_helper')->archiveObjects();
}

