<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BloggingModule\HookSubscriber;

use MU\BloggingModule\HookSubscriber\Base\AbstractPostFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class PostFormAwareHookSubscriber extends AbstractPostFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
