services:
    mu_blogging_module.app_settings:
        class: MU\BloggingModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
