services:
    # Content types
    MU\BloggingModule\ContentType\ItemListType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setControllerHelper, ['@mu_blogging_module.controller_helper']]
            - [setModelHelper, ['@mu_blogging_module.model_helper']]
            - [setEntityFactory, ['@mu_blogging_module.entity_factory']]
            - [setCategoryDependencies, ['@mu_blogging_module.feature_activation_helper', '@mu_blogging_module.category_helper']]
        tags: ['zikula.content_type']
    MU\BloggingModule\ContentType\Form\Type\ItemListType:
        parent: zikula.content_type.form.base
        arguments:
            - "@zikula_categories_module.category_repository"
        tags: ['form.type']
    MU\BloggingModule\ContentType\ItemType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setControllerHelper, ['@mu_blogging_module.controller_helper']]
            - [setFragmentHandler, ['@fragment.handler']]
        tags: ['zikula.content_type']
    MU\BloggingModule\ContentType\Form\Type\ItemType:
        parent: zikula.content_type.form.base
        arguments:
            - "@mu_blogging_module.entity_factory"
            - "@mu_blogging_module.entity_display_helper"
        tags: ['form.type']
