services:
    # Entity factory
    mu_blogging_module.entity_factory:
        class: MU\BloggingModule\Entity\Factory\BloggingFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@mu_blogging_module.entity_initialiser"
    # Entity initialiser
    mu_blogging_module.entity_initialiser:
        class: MU\BloggingModule\Entity\Factory\EntityInitialiser
        arguments:
            - "@mu_blogging_module.listentries_helper"
