<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractimage_info.php';

/**
 * MUBloggingModule image needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUBloggingModule_needleapi_image_info()
{
    return MUBloggingModule_needleapi_image_baseInfo();
}
