<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\Form\Type;

use MU\BloggingModule\Form\Type\Base\AbstractImageType;

/**
 * Image editing form type implementation class.
 */
class ImageType extends AbstractImageType
{
    // feel free to extend the image editing form type class here
}
