<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\BloggingModule\Form\Type;

use MU\BloggingModule\Form\Type\Base\AbstractPostType;

/**
 * Post editing form type implementation class.
 */
class PostType extends AbstractPostType
{
    // feel free to extend the post editing form type class here
}
