<?php
/**
 * Blogging.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\BloggingModule\TaggedObjectMeta;

use MU\BloggingModule\TaggedObjectMeta\Base\AbstractMUBloggingModule;

/**
 * This class provides object meta data for the Tag module.
 */
class MUBloggingModule extends AbstractMUBloggingModule
{
    // feel free to extend the tag support here
}
